
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = "\xc8\xac\xe7\xee 1\x8f\xd2\xcd9\xa3\x91\xfd\x81'\x92"
    
_lr_action_items = {'AND':([21,22,32,33,36,37,39,40,],[-18,29,29,-17,-19,-14,29,-16,]),'THEN':([21,22,33,36,37,39,40,],[-18,30,-17,-19,-14,-15,-16,]),'RPAREN':([21,32,33,36,37,39,40,50,51,],[-18,40,-17,-19,-14,-15,-16,52,53,]),'UNIVERSE':([0,1,5,7,18,46,],[2,2,-3,-2,-5,-4,]),'IS':([20,],[28,]),'ALGORITHM_TYPE':([0,1,5,7,18,46,],[3,3,-3,-2,-5,-4,]),'EQUALS':([2,3,25,],[10,11,34,]),'ELSE':([12,14,27,36,38,],[-12,19,-11,-19,-13,]),'NUMBER':([10,26,42,43,44,48,49,],[17,35,45,46,47,50,51,]),'COMMA':([17,35,45,47,],[26,43,48,49,]),'LPAREN':([15,23,24,29,31,34,41,52,53,],[23,23,23,23,23,42,44,-10,-9,]),'OR':([21,22,32,33,36,37,39,40,],[-18,31,31,-17,-19,-14,-15,-16,]),'NOT':([15,23,24,29,31,],[24,24,24,24,24,]),'IF':([6,8,13,19,41,52,53,],[15,-7,-6,15,-8,-10,-9,]),'ID':([1,5,6,7,8,11,13,15,16,18,23,24,28,29,30,31,41,46,52,53,],[9,-3,9,-2,-7,18,-6,20,25,-5,20,20,36,20,20,20,-8,-4,-10,-9,]),'DOT':([9,],[16,]),'$end':([4,12,14,27,36,38,],[0,-12,-1,-11,-19,-13,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'settings':([0,],[1,]),'declarations':([1,],[6,]),'preposition':([15,23,24,29,30,31,],[21,21,21,21,38,21,]),'program':([0,],[4,]),'compose_preposition':([15,23,24,29,31,],[22,32,33,37,39,]),'statement':([6,19,],[12,27,]),'declaration':([1,6,],[8,13,]),'statement_list':([6,],[14,]),'params':([34,],[41,]),'setting':([0,1,],[5,7,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> settings declarations statement_list','program',3,'p_program','/home/ariel/Documents/repos/parser_fuzzy/parser_fuzzy.py',71),
  ('settings -> settings setting','settings',2,'p_settings','/home/ariel/Documents/repos/parser_fuzzy/parser_fuzzy.py',76),
  ('settings -> setting','settings',1,'p_settings','/home/ariel/Documents/repos/parser_fuzzy/parser_fuzzy.py',77),
  ('setting -> UNIVERSE EQUALS NUMBER COMMA NUMBER COMMA NUMBER','setting',7,'p_universe_declaration','/home/ariel/Documents/repos/parser_fuzzy/parser_fuzzy.py',82),
  ('setting -> ALGORITHM_TYPE EQUALS ID','setting',3,'p_implication_type','/home/ariel/Documents/repos/parser_fuzzy/parser_fuzzy.py',87),
  ('declarations -> declarations declaration','declarations',2,'p_declarations_list','/home/ariel/Documents/repos/parser_fuzzy/parser_fuzzy.py',92),
  ('declarations -> declaration','declarations',1,'p_declarations_list','/home/ariel/Documents/repos/parser_fuzzy/parser_fuzzy.py',93),
  ('declaration -> ID DOT ID EQUALS params','declaration',5,'p_declaration','/home/ariel/Documents/repos/parser_fuzzy/parser_fuzzy.py',98),
  ('params -> params LPAREN NUMBER COMMA NUMBER RPAREN','params',6,'p_params','/home/ariel/Documents/repos/parser_fuzzy/parser_fuzzy.py',108),
  ('params -> LPAREN NUMBER COMMA NUMBER RPAREN','params',5,'p_params','/home/ariel/Documents/repos/parser_fuzzy/parser_fuzzy.py',109),
  ('statement_list -> statement_list ELSE statement','statement_list',3,'p_statement_list_l','/home/ariel/Documents/repos/parser_fuzzy/parser_fuzzy.py',117),
  ('statement_list -> statement','statement_list',1,'p_statement_list_s','/home/ariel/Documents/repos/parser_fuzzy/parser_fuzzy.py',122),
  ('statement -> IF compose_preposition THEN preposition','statement',4,'p_statement','/home/ariel/Documents/repos/parser_fuzzy/parser_fuzzy.py',127),
  ('compose_preposition -> compose_preposition AND compose_preposition','compose_preposition',3,'p_preposition_binary','/home/ariel/Documents/repos/parser_fuzzy/parser_fuzzy.py',139),
  ('compose_preposition -> compose_preposition OR compose_preposition','compose_preposition',3,'p_preposition_binary','/home/ariel/Documents/repos/parser_fuzzy/parser_fuzzy.py',140),
  ('compose_preposition -> LPAREN compose_preposition RPAREN','compose_preposition',3,'p_preposition_paren','/home/ariel/Documents/repos/parser_fuzzy/parser_fuzzy.py',148),
  ('compose_preposition -> NOT compose_preposition','compose_preposition',2,'p_preposition_not','/home/ariel/Documents/repos/parser_fuzzy/parser_fuzzy.py',153),
  ('compose_preposition -> preposition','compose_preposition',1,'p_compose_preposition_preposition','/home/ariel/Documents/repos/parser_fuzzy/parser_fuzzy.py',159),
  ('preposition -> ID IS ID','preposition',3,'p_preposition_is','/home/ariel/Documents/repos/parser_fuzzy/parser_fuzzy.py',166),
]
